### PR TITLE
WIP: Update tests

### PR DESCRIPTION
**Pull request by nicolaiskogheim**
Hi!

In an attempt to familiarize myself with this code base I'm trying to update the tests, which broke when the `*Template` structs and package `generator` changed.

I moved the tests into package `template` to get access to unexported structs that the tests use, but now I have an import cycle violation

```sh
$ go test ./generator/template
# github.com/devimteam/microgen/generator/template
import cycle not allowed in test
package github.com/devimteam/microgen/generator/template (test)
	imports github.com/devimteam/microgen/generator
	imports github.com/devimteam/microgen/generator/template

FAIL	github.com/devimteam/microgen/generator/template [setup failed]
```

-----

I just now saw that we can get those unexported structs through some new constructor methods, hehe, I guess I'll use those, and maybe move the tests back out again.

I.e.

```go
type endpointsTemplate struct {
	Info *GenerationInfo
}

func NewEndpointsTemplate(info *GenerationInfo) Template {
	return &endpointsTemplate{
		Info: info,
	}
}
```

-----

Anyway, I just wanted to let you know that I was working on this, in case you have any feedback of sorts.

### CODE REVIEW

**Comment by nicolaiskogheim** [comment]
I hit <kbd>Enter</kbd> too quick. Updates to OP comig.

**Comment by nicolaiskogheim** [comment]
It's currently not possible so set or override the write strategy (`Template.WriteStrategy`) of templates, which forces me to read the test files.

In the future maybe it should be possible to set `WriteStrategy` somewhere, and/or the tests could use a fake filesystem.

**Comment by Vetcher** [comment]
merge #38

**Comment by nicolaiskogheim** [comment]
Great!

**Pull request closed without merging**
